


import { Ticket, TicketType, Status, Priority, ProductArea, Platform, TaskStatus, Dealership, DealershipStatus, TaskPriority, Task, FeatureAnnouncement, FeatureStatus, Meeting, Contact, ContactType, ContactGroup, DealershipGroup, KnowledgeArticle, Shopper, RecentActivity, IssueTicket, FeatureRequestTicket, Update, Release, ReleaseStatus } from './types.ts';

export const initialTickets: Ticket[] = [
  {
    id: '1',
    type: TicketType.Issue,
    productArea: ProductArea.Reynolds,
    platform: Platform.Curator,
    title: 'Login button unresponsive on Safari',
    client: 'ABC Motors',
    pmrNumber: 'PMR-12345',
    pmrLink: 'https://example.com/pmr/12345',
    fpTicketNumber: 'FP-001',
    ticketThreadId: 'THREAD-ABC-123',
    // FIX: Added submissionDate to match the updated Ticket type.
    submissionDate: new Date('2024-07-21T09:00:00Z').toISOString(),
    lastUpdatedDate: new Date('2024-07-23T15:30:00Z').toISOString(),
    startDate: new Date('2024-07-21T09:00:00Z').toISOString(),
    status: Status.InProgress,
    priority: Priority.P1,
    submitterName: 'Alice Johnson',
    location: 'Login Page',
    problem: 'The main login button does not respond to clicks on Safari 15.2 and newer. No errors are thrown in the console.',
    duplicationSteps: '1. Open Safari 15.2+. 2. Navigate to the login page. 3. Enter credentials. 4. Click the "Log In" button. Nothing happens.',
    workaround: 'Users can press the Enter key after filling in the password field to log in successfully.',
    frequency: 'Occurs 100% of the time for affected users.',
    linkedTicketIds: ['5'],
    updates: [
      {
        id: 'update-1-1',
        author: 'Dev Team',
        date: new Date('2024-07-22T11:00:00Z').toISOString(),
        comment: 'Assigned to John Doe. Starting investigation.'
      },
      {
        id: 'update-1-2',
        author: 'John Doe',
        date: new Date('2024-07-23T15:30:00Z').toISOString(),
        comment: 'Identified the issue is related to event propagation in WebKit. Working on a fix.'
      }
    ],
    tasks: [],
    meetingIds: [],
    taskIds: [],
    dealershipIds: [],
    featureIds: [],
    shopperIds: ['shopper-1'],
  } as IssueTicket,
  {
    id: '2',
    type: TicketType.FeatureRequest,
    productArea: ProductArea.Fullpath,
    platform: Platform.UCP,
    title: 'Implement Dark Mode',
    client: 'Luxury Auto Group',
    pmrNumber: 'PMR-67890',
    fpTicketNumber: 'FP-002',
    ticketThreadId: 'THREAD-DEF-456',
    // FIX: Added submissionDate to match the updated Ticket type.
    submissionDate: new Date('2024-07-15T09:00:00Z').toISOString(),
    lastUpdatedDate: new Date('2024-07-18T09:00:00Z').toISOString(),
    startDate: new Date('2024-07-18T09:00:00Z').toISOString(),
    status: Status.InReview,
    priority: Priority.P5,
    submitterName: 'Bob Williams',
    location: 'Entire Application',
    improvement: 'Add a user-selectable dark mode theme to the application.',
    currentFunctionality: 'The application currently only has a light theme, which can cause eye strain in low-light environments.',
    suggestedSolution: 'Implement a theme switcher in the user settings that toggles CSS variables for colors across the entire UI.',
    benefits: 'Improved user experience, reduced eye strain, modern look and feel, and better accessibility for some users.',
    updates: [
      {
        id: 'update-2-1',
        author: 'Product Team',
        date: new Date('2024-07-16T10:00:00Z').toISOString(),
        comment: 'Feature request has been received and is under review for the next quarter planning.'
      }
    ],
    tasks: [],
    linkedTicketIds: [],
    meetingIds: ['meet-1'],
    taskIds: [],
    dealershipIds: [],
    featureIds: [],
    isFavorite: true,
  } as FeatureRequestTicket,
  {
    id: '3',
    type: TicketType.Issue,
    productArea: ProductArea.Reynolds,
    platform: Platform.FOCUS,
    title: 'User profile picture not updating',
    client: 'Community Cars',
    fpTicketNumber: 'FP-003',
    ticketThreadId: 'THREAD-GHI-789',
    // FIX: Added submissionDate to match the updated Ticket type.
    submissionDate: new Date('2024-07-22T09:00:00Z').toISOString(),
    lastUpdatedDate: new Date('2024-07-22T09:00:00Z').toISOString(),
    status: Status.NotStarted,
    priority: Priority.P2,
    submitterName: 'Charlie Brown',
    location: 'User Profile Settings',
    problem: 'When a user uploads a new profile picture, the old one remains visible until they clear their browser cache.',
    duplicationSteps: '1. Go to profile settings. 2. Upload a new avatar. 3. Observe that the old avatar is still displayed.',
    workaround: 'Perform a hard refresh (Ctrl+Shift+R) or clear the browser cache.',
    frequency: 'Always.',
    updates: [],
    tasks: [],
    linkedTicketIds: [],
    meetingIds: [],
    taskIds: [],
    dealershipIds: [],
    featureIds: [],
  } as IssueTicket,
  {
    id: '4',
    type: TicketType.Issue,
    productArea: ProductArea.Fullpath,
    platform: Platform.Curator,
    title: 'Export to CSV functionality is broken on Firefox',
    client: 'Prestige Imports',
    pmrNumber: 'PMR-55555',
    fpTicketNumber: 'FP-004',
    ticketThreadId: 'THREAD-JKL-101',
    // FIX: Added submissionDate to match the updated Ticket type.
    submissionDate: new Date('2024-07-10T09:00:00Z').toISOString(),
    lastUpdatedDate: new Date('2024-07-25T16:00:00Z').toISOString(),
    completionDate: new Date('2024-07-25T16:00:00Z').toISOString(),
    status: Status.Completed,
    priority: Priority.P2,
    submitterName: 'Diana Prince',
    location: 'Reports Page',
    problem: 'The "Export to CSV" button triggers a download, but the resulting file is corrupted and cannot be opened in any spreadsheet software. This issue is specific to Firefox.',
    duplicationSteps: '1. Log in using Firefox. 2. Go to the "Reports" section. 3. Generate any report. 4. Click "Export to CSV". 5. Try to open the downloaded file.',
    workaround: 'Use a different browser like Chrome or Edge.',
    frequency: 'Always on Firefox.',
    updates: [
        { id: 'update-4-1', author: 'QA Team', date: new Date('2024-07-11T09:00:00Z').toISOString(), comment: 'Confirmed and reproduced the issue. Root cause seems to be related to MIME type handling on Firefox.' },
        { id: 'update-4-2', author: 'Dev Team', date: new Date('2024-07-12T14:20:00Z').toISOString(), comment: 'Fix has been implemented and deployed to staging for verification.' },
        { id: 'update-4-3', author: 'QA Team', date: new Date('2024-07-13T11:00:00Z').toISOString(), comment: 'Verified the fix on staging. Issue is resolved. Marking as complete.' }
    ],
    completionNotes: 'The fix involved correcting the Blob constructor to explicitly set the MIME type to "text/csv;charset=utf-8;". This ensures Firefox correctly interprets the file format upon download. The change was deployed in patch v2.3.1.',
    tasks: [],
    linkedTicketIds: [],
    meetingIds: [],
    taskIds: [],
    dealershipIds: [],
    featureIds: [],
  } as IssueTicket,
  {
    id: '5',
    type: TicketType.Issue,
    productArea: ProductArea.Fullpath,
    platform: Platform.UCP,
    title: 'API endpoint timing out',
    client: 'Global Auto',
    // FIX: Added submissionDate to match the updated Ticket type.
    submissionDate: new Date('2024-07-28T09:00:00Z').toISOString(),
    lastUpdatedDate: new Date('2024-07-28T10:00:00Z').toISOString(),
    status: Status.OnHold,
    onHoldReason: 'Waiting for dependency on external API to be resolved by their team. ETA: 2 weeks.',
    priority: Priority.P2,
    submitterName: 'Edward Snowden',
    location: 'Backend API service',
    problem: 'The /api/v2/inventory endpoint is frequently timing out under moderate load.',
    duplicationSteps: '1. Send 10 concurrent requests to the endpoint. 2. Observe 504 Gateway Timeout errors.',
    workaround: 'None.',
    frequency: 'During peak hours.',
    linkedTicketIds: ['1'],
    updates: [],
    tasks: [],
    meetingIds: [],
    taskIds: [],
    dealershipIds: [],
    featureIds: [],
  } as IssueTicket
];

export const initialTasks: Task[] = [
  {
    id: 'task-1',
    description: 'Update the company-wide design system documentation',
    assignedUser: 'Jane Doe',
    status: TaskStatus.InProgress,
    priority: TaskPriority.P2,
    type: 'Documentation',
    creationDate: new Date('2024-07-20T10:00:00Z').toISOString(),
    dueDate: new Date('2024-08-15T17:00:00Z').toISOString(),
    notifyOnCompletion: 'design-team@example.com',
    linkedTaskIds: [],
    ticketIds: [],
    meetingIds: [],
    dealershipIds: [],
    featureIds: [],
    shopperIds: ['shopper-2'],
  },
  {
    id: 'task-2',
    description: 'Plan the team offsite for Q4',
    assignedUser: 'John Doe',
    status: TaskStatus.ToDo,
    priority: TaskPriority.P4,
    type: 'Planning',
    creationDate: new Date('2024-07-21T10:00:00Z').toISOString(),
    linkedTaskIds: [],
    ticketIds: [],
    meetingIds: [],
    dealershipIds: [],
    featureIds: [],
  }
];

export const initialDealerships: Dealership[] = [
  {
    id: 'dealership-1',
    name: 'Prestige Motors',
    accountNumber: 'CIF-1001',
    status: DealershipStatus.Live,
    hasManagedSolution: true,
    wasFullpathCustomer: true,
    orderNumber: 'ORD-2024-001',
    orderReceivedDate: new Date('2024-01-15T00:00:00Z').toISOString(),
    goLiveDate: new Date('2024-02-01T00:00:00Z').toISOString(),
    enterprise: 'Luxury Auto Group',
    storeNumber: 'S-01',
    branchNumber: 'B-01',
    eraSystemId: 'ERA-PM-01',
    ppSysId: 'PPSYS-PM-01',
    buId: 'BU-PM-01',
    address: '123 Luxury Lane, Beverly Hills, CA 90210',
    assignedSpecialist: 'John Smith',
    sales: 'Sarah Conner',
    pocName: 'Mike Miller',
    pocEmail: 'mike.miller@prestigemotors.com',
    pocPhone: '555-123-4567',
    websiteLinks: [
      { url: 'https://www.prestigemotors.com', clientId: 'PM-WEB-01' },
      { url: 'https://inventory.prestigemotors.com', clientId: 'PM-INV-01' }
    ],
    updates: [
      {
        id: 'update-deal-1-1',
        author: 'John Smith',
        date: new Date('2024-02-15T10:00:00Z').toISOString(),
        comment: 'Initial setup call completed. Client is excited to get started.'
      },
      {
        id: 'update-deal-1-2',
        author: 'Mike Miller (Client)',
        date: new Date('2024-03-01T14:30:00Z').toISOString(),
        comment: 'Training for sales team went well. A few questions about the reporting dashboard.'
      }
    ],
    groupIds: ['d-group-1'],
    ticketIds: [],
    meetingIds: [],
    taskIds: [],
    linkedDealershipIds: [],
    featureIds: [],
    shopperIds: ['shopper-1'],
  },
  {
    id: 'dealership-2',
    name: 'City Cars',
    accountNumber: 'CIF-1002',
    status: DealershipStatus.Onboarding,
    hasManagedSolution: true,
    wasFullpathCustomer: false,
    orderNumber: 'ORD-2024-002',
    orderReceivedDate: new Date('2024-07-01T00:00:00Z').toISOString(),
    goLiveDate: new Date('2024-08-01T00:00:00Z').toISOString(),
    enterprise: 'Urban Motors Inc.',
    storeNumber: 'S-05',
    branchNumber: 'B-10',
    address: '456 Main Street, Anytown, USA 12345',
    assignedSpecialist: 'Jane Doe',
    sales: 'Bill Paxton',
    pocName: 'Anna Williams',
    pocEmail: 'anna.w@citycars.com',
    pocPhone: '555-987-6543',
    websiteLinks: [{ url: 'https://www.citycars.com', clientId: 'CC-MAIN-34' }],
    updates: [],
    groupIds: ['d-group-2'],
    ticketIds: [],
    meetingIds: [],
    taskIds: [],
    linkedDealershipIds: [],
    featureIds: [],
    shopperIds: ['shopper-2'],
  },
  {
    id: 'dealership-3',
    name: 'Reliable Rides',
    accountNumber: 'CIF-1003',
    status: DealershipStatus.Cancelled,
    hasManagedSolution: false,
    wasFullpathCustomer: true,
    orderNumber: 'ORD-2023-050',
    orderReceivedDate: new Date('2023-10-01T00:00:00Z').toISOString(),
    goLiveDate: new Date('2023-11-01T00:00:00Z').toISOString(),
    termDate: new Date('2024-06-30T00:00:00Z').toISOString(),
    enterprise: 'Value Vehicles',
    address: '789 Budget Ave, Thriftyville, TX 75001',
    assignedSpecialist: 'Peter Jones',
    sales: 'Rick Deckard',
    pocName: 'Rachael',
    pocEmail: 'rachael@tyrellcorp.com',
    pocPhone: '555-555-5555',
    updates: [],
    ticketIds: [],
    meetingIds: [],
    taskIds: [],
    linkedDealershipIds: [],
    featureIds: [],
  },
  {
    id: 'dealership-4',
    name: 'Future Fleet',
    accountNumber: 'CIF-1004',
    status: DealershipStatus.Pilot,
    wasFullpathCustomer: false,
    orderNumber: 'ORD-2024-004',
    orderReceivedDate: new Date('2024-07-15T00:00:00Z').toISOString(),
    goLiveDate: new Date('2024-09-01T00:00:00Z').toISOString(),
    enterprise: 'NextGen Auto',
    address: '1 Innovation Drive, Tech City, USA 54321',
    assignedSpecialist: 'Susan Storm',
    sales: 'Reed Richards',
    pocName: 'Ben Grimm',
    pocEmail: 'b.grimm@ff.com',
    pocPhone: '555-444-4444',
    updates: [],
    ticketIds: [],
    meetingIds: [],
    taskIds: [],
    linkedDealershipIds: [],
    featureIds: [],
  },
  {
    id: 'dealership-5',
    name: 'Focus Forward',
    accountNumber: 'CIF-1005',
    status: DealershipStatus.PendingFocus,
    wasFullpathCustomer: false,
    orderNumber: 'ORD-2024-005',
    orderReceivedDate: new Date('2024-07-20T00:00:00Z').toISOString(),
    enterprise: 'Urban Motors Inc.',
    address: '2 Tech Way, Anytown, USA 12345',
    assignedSpecialist: 'Jane Doe',
    updates: [],
    groupIds: ['d-group-2'],
    ticketIds: [],
    meetingIds: [],
    taskIds: [],
    linkedDealershipIds: [],
    featureIds: [],
  },
  {
    id: 'dealership-6',
    name: 'DMT Dynamics',
    accountNumber: 'CIF-1006',
    status: DealershipStatus.PendingDmt,
    wasFullpathCustomer: true,
    orderNumber: 'ORD-2024-006',
    orderReceivedDate: new Date('2024-07-22T00:00:00Z').toISOString(),
    enterprise: 'Value Vehicles',
    address: '3 Integration Blvd, Thriftyville, TX 75001',
    assignedSpecialist: 'Peter Jones',
    updates: [],
    ticketIds: [],
    meetingIds: [],
    taskIds: [],
    linkedDealershipIds: [],
    featureIds: [],
  },
  {
    id: 'dealership-7',
    name: 'Setup Solutions',
    accountNumber: 'CIF-1007',
    status: DealershipStatus.PendingSetup,
    wasFullpathCustomer: false,
    orderNumber: 'ORD-2024-007',
    orderReceivedDate: new Date('2024-07-25T00:00:00Z').toISOString(),
    enterprise: 'NextGen Auto',
    address: '4 Config Ct, Tech City, USA 54321',
    assignedSpecialist: 'Susan Storm',
    updates: [],
    ticketIds: [],
    meetingIds: [],
    taskIds: [],
    linkedDealershipIds: [],
    featureIds: [],
  },
  {
    id: 'dealership-8',
    name: 'Future Horizons Automotive',
    accountNumber: 'CIF-1008',
    status: DealershipStatus.Prospect,
    wasFullpathCustomer: false,
    enterprise: 'Visionary Motors',
    sales: 'Sarah Conner',
    pocName: 'John Anderton',
    pocEmail: 'j.anderton@futurehorizons.com',
    updates: [],
    ticketIds: [],
    meetingIds: [],
    taskIds: [],
    linkedDealershipIds: [],
    featureIds: [],
  },
];

export const initialFeatures: FeatureAnnouncement[] = [
  {
    id: 'feat-1',
    title: 'Dark Mode',
    location: 'Entire Application',
    description: 'A new dark mode theme has been introduced to reduce eye strain in low-light environments. You can enable it from your user settings.',
    launchDate: new Date('2024-08-15T00:00:00Z').toISOString(),
    version: 'v3.0.0',
    platform: Platform.UCP,
    status: FeatureStatus.Launched,
    categories: ['UI/UX', 'Accessibility'],
    successMetrics: '50% user adoption within 3 months. Reduction in user-reported eye strain complaints.',
    targetAudience: 'All users, especially those working in low-light conditions or with visual sensitivities.',
    supportUrl: 'https://example.com/support/dark-mode',
    updates: [
        {
            id: 'update-feat-1-1',
            author: 'UX Team',
            date: new Date('2024-07-20T10:00:00Z').toISOString(),
            comment: 'Final design patterns approved.'
        }
    ],
    ticketIds: [],
    meetingIds: [],
    taskIds: [],
    dealershipIds: [],
    linkedFeatureIds: [],
  },
  {
    id: 'feat-2',
    title: 'Project Task Drag & Drop',
    location: 'Project Detail View',
    description: 'You can now reorder tasks within a project by simply dragging and dropping them. This makes organizing your project workflow more intuitive.',
    launchDate: new Date('2024-08-01T00:00:00Z').toISOString(),
    version: 'v2.9.0',
    platform: Platform.Curator,
    status: FeatureStatus.Launched,
    categories: ['UI/UX', 'Project Management'],
    successMetrics: 'Increase in task reordering actions by 20%. Positive feedback in user surveys.',
    targetAudience: 'Project managers and team members.',
    supportUrl: 'https://example.com/support/drag-drop',
    ticketIds: [],
    meetingIds: [],
    taskIds: [],
    dealershipIds: [],
    linkedFeatureIds: [],
  },
  {
    id: 'feat-3',
    title: 'Advanced Reporting Filters',
    location: 'Reports Page',
    description: 'We are adding more granular filtering options to the reporting suite, allowing you to create more specific and insightful reports. This will include filtering by custom date ranges and additional ticket properties.',
    launchDate: new Date('2024-09-01T00:00:00Z').toISOString(),
    platform: Platform.Curator,
    status: FeatureStatus.InDevelopment,
    categories: ['Reporting', 'Data Analysis'],
    successMetrics: 'Users generate 30% more custom reports. Decrease in requests for custom report generation from support.',
    targetAudience: 'Managers, Analysts, and Account Executives.',
    ticketIds: [],
    meetingIds: [],
    taskIds: [],
    dealershipIds: [],
    linkedFeatureIds: [],
  },
  {
    id: 'feat-4',
    title: 'API Rate Limiting',
    location: 'Backend API',
    description: 'Implement rate limiting on public API endpoints to ensure stability and prevent abuse.',
    launchDate: new Date('2024-10-01T00:00:00Z').toISOString(),
    platform: Platform.Curator,
    status: FeatureStatus.Upcoming,
    categories: ['API', 'Performance', 'Security'],
    successMetrics: 'No API downtime caused by traffic spikes. Fair usage across all API clients.',
    targetAudience: 'Third-party developers and integrators.',
    ticketIds: [],
    meetingIds: [],
    taskIds: [],
    dealershipIds: [],
    linkedFeatureIds: [],
  },
  {
    id: 'feat-5',
    title: 'Real-time Collaboration on Meeting Notes',
    location: 'Meeting Notes View',
    description: 'Allow multiple users to edit meeting notes simultaneously, similar to Google Docs.',
    launchDate: new Date('2025-01-15T00:00:00Z').toISOString(),
    platform: Platform.Curator,
    status: FeatureStatus.InDiscovery,
    categories: ['Collaboration', 'UI/UX'],
    successMetrics: 'Increased usage of meeting notes feature. Positive qualitative feedback.',
    targetAudience: 'All teams participating in meetings.',
    ticketIds: [],
    meetingIds: [],
    taskIds: [],
    dealershipIds: [],
    linkedFeatureIds: [],
  },
   {
    id: 'feat-6',
    title: 'SSO Integration (SAML)',
    location: 'Login & Authentication',
    description: 'Provide support for Single Sign-On (SSO) using the SAML 2.0 protocol to allow enterprise customers to manage their own user access.',
    launchDate: new Date('2024-11-01T00:00:00Z').toISOString(),
    platform: Platform.UCP,
    status: FeatureStatus.Backlog,
    categories: ['Security', 'Authentication'],
    successMetrics: 'Onboard 5 major enterprise clients using SSO within 6 months.',
    targetAudience: 'Enterprise-level customers with internal identity providers.',
    ticketIds: [],
    meetingIds: [],
    taskIds: [],
    dealershipIds: [],
    linkedFeatureIds: [],
  },
  {
    id: 'feat-7',
    title: 'Mobile Responsiveness Overhaul',
    location: 'Entire Application',
    description: 'Conduct a full audit and update of all pages to ensure they are fully responsive and usable on mobile devices.',
    launchDate: new Date('2024-09-20T00:00:00Z').toISOString(),
    platform: Platform.Curator,
    status: FeatureStatus.Testing,
    categories: ['UI/UX', 'Mobile'],
    successMetrics: 'Achieve a Lighthouse accessibility and performance score of 90+ on key pages. Increase in mobile session duration by 15%.',
    targetAudience: 'All users, especially those accessing the app on tablets and phones.',
    ticketIds: [],
    meetingIds: [],
    taskIds: [],
    dealershipIds: [],
    linkedFeatureIds: [],
  }
];

export const initialMeetings: Meeting[] = [
  {
    id: 'meet-1',
    name: 'Project Kickoff: Dark Mode',
    meetingDate: new Date('2024-07-11T10:00:00Z').toISOString(),
    attendees: ['Project Lead', 'John Doe', 'UX Team'],
    notes: '<h3>Agenda</h3><ul><li>Finalize design specs</li><li>Outline development tasks</li><li>Set timeline</li></ul><p>Discussion points were positive. Team is aligned.</p>',
    ticketIds: ['2'],
    linkedMeetingIds: [],
    taskIds: [],
    dealershipIds: [],
    featureIds: [],
  },
  {
    id: 'meet-2',
    name: 'Compliance Audit Weekly Sync',
    meetingDate: new Date('2024-07-28T14:00:00Z').toISOString(),
    attendees: ['Security Team', 'DevOps', 'Legal Advisor'],
    notes: '<p>Reviewed progress on log gathering. DevOps to provide an update on encryption verification by EOW.</p>',
    ticketIds: [],
    linkedMeetingIds: [],
    taskIds: [],
    dealershipIds: [],
    featureIds: [],
  }
];

export const initialContacts: Contact[] = [
  { id: 'contact-1', name: 'John Doe', email: 'john.doe@internal.com', role: 'Lead Developer', type: ContactType.Internal, isFavorite: true, groupIds: ['group-1'] },
  { id: 'contact-2', name: 'Alice Johnson', email: 'alice.j@internal.com', role: 'Frontend Developer', type: ContactType.Internal, groupIds: ['group-1'] },
  { id: 'contact-3', name: 'Bob Williams', email: 'bob.w@internal.com', role: 'Project Manager', type: ContactType.Internal },
  { id: 'contact-4', name: 'Mike Miller', email: 'mike.miller@prestigemotors.com', role: 'Client POC', type: ContactType.External, phone: '555-123-4567', groupIds: ['group-2'] },
  { id: 'contact-5', name: 'Anna Williams', email: 'anna.w@citycars.com', role: 'General Manager', type: ContactType.External, phone: '555-987-6543', groupIds: ['group-2'] },
];

export const initialContactGroups: ContactGroup[] = [
  { id: 'group-1', name: 'Development Team', description: 'Core engineers for the Curator project.', contactIds: ['contact-1', 'contact-2'] },
  { id: 'group-2', name: 'Key Client Contacts', description: 'Main points of contact for our top clients.', contactIds: ['contact-4', 'contact-5'] },
];

export const initialDealershipGroups: DealershipGroup[] = [
  { id: 'd-group-1', name: 'Luxury Auto Group', description: 'High-end dealerships.', dealershipIds: ['dealership-1'] },
  { id: 'd-group-2', name: 'Urban Motors Inc.', description: 'Dealerships located in metropolitan areas.', dealershipIds: ['dealership-2', 'dealership-5'] },
];

export const initialKnowledgeArticles: KnowledgeArticle[] = [
    {
        id: 'kb-1',
        title: 'Onboarding Checklist for New Clients',
        content: '<h3>Phase 1: Pre-Kickoff</h3><ul><li>Send welcome email</li><li>Schedule kickoff call</li><li>Grant system access</li></ul><h3>Phase 2: Post-Kickoff</h3><ol><li>Complete user training</li><li>Set up initial reports</li><li>Schedule first check-in</li></ol>',
        tags: ['onboarding', 'checklist', 'client-success'],
        category: 'Process',
        createdDate: new Date('2024-07-20T10:00:00Z').toISOString(),
        lastModifiedDate: new Date('2024-07-22T11:00:00Z').toISOString(),
        isFavorite: true,
    },
    {
        id: 'kb-2',
        title: 'Common Safari CSS Bugs',
        content: '<p>Safari can be tricky. Here are a few common issues:</p><p><strong>1. Flexbox alignment:</strong> Sometimes requires explicit `align-items` settings.</p><p><strong>2. `vh` units in modals:</strong> Can cause sizing issues due to the browser UI. Use JavaScript to calculate height instead.</p>',
        tags: ['css', 'safari', 'frontend', 'bugs'],
        category: 'Technical',
        createdDate: new Date('2024-07-15T14:30:00Z').toISOString(),
        lastModifiedDate: new Date('2024-07-15T14:30:00Z').toISOString(),
    }
];

export const initialShoppers: Shopper[] = [
  {
    id: 'shopper-1',
    customerName: 'Jane Smith',
    curatorId: 'CUR-98765',
    curatorLink: 'https://example.com/curator/98765',
    email: 'jane.smith@example.com',
    phone: '555-111-2222',
    cdpId: 'CDP-JSMITH',
    dmsId: 'DMS-456',
    uniqueIssue: 'User is unable to see vehicle pricing on VDPs. Console shows a 403 error on the pricing API endpoint.',
    recentActivity: [
      {
        id: 'act-1-1',
        date: '2024-07-28',
        time: '10:30 AM',
        activity: 'Visited VDP for 2024 Ford F-150',
        action: 'Clicked on "Get E-Price", no price displayed',
      },
      {
        id: 'act-1-2',
        date: '2024-07-28',
        time: '10:32 AM',
        activity: 'Navigated to inventory search',
        action: 'Performed search for "Ford"',
      }
    ],
    dealershipIds: ['dealership-1'],
    ticketIds: ['1'],
    isFavorite: true,
  },
  {
    id: 'shopper-2',
    customerName: 'John Appleseed',
    curatorId: 'CUR-12345',
    email: 'john.a@example.com',
    uniqueIssue: 'Trade-in value form is not accepting VIN.',
    dealershipIds: ['dealership-2'],
    ticketIds: [],
    taskIds: ['task-1'],
    isFavorite: false,
  }
];

export const initialReleases: Release[] = [
  {
    id: 'rel-1',
    name: 'Q3 Feature Drop',
    version: 'v3.0.0',
    releaseDate: new Date('2024-09-15T00:00:00Z').toISOString(),
    status: ReleaseStatus.InProgress,
    description: 'Major release including Dark Mode and performance improvements.',
    featureIds: ['feat-1', 'feat-2', 'feat-3'],
    ticketIds: ['2', '4'],
  },
  {
    id: 'rel-2',
    name: 'Q4 Security Patch',
    version: 'v3.1.0',
    releaseDate: new Date('2024-11-01T00:00:00Z').toISOString(),
    status: ReleaseStatus.Planned,
    description: 'Security enhancements including SSO and API rate limiting.',
    featureIds: ['feat-6', 'feat-4'],
  },
];